import { Inter } from 'next/font/google';
import { Box } from '@mui/material';
import Sidenav from '@/components/Sidenav/Sidenav';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import CssBaseline from '@mui/material/CssBaseline';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <CssBaseline />

        <Box sx={{ height: '100%' }}>
          <Sidenav />

          <Box
            sx={{
              ml: 11,
              p: 2,
              minHeight: '100%',
              display: 'flex',
              flexDirection: 'column',
              gap: 2
            }}
          >
            <Header />

            <Box sx={{ flex: '1 0 auto' }}>{children}</Box>

            <Footer />
          </Box>
        </Box>
      </body>
    </html>
  );
}
