'use client';

import React, { useState } from 'react';
import { Inter } from 'next/font/google';
import { styled } from '@mui/system';
import { Alert, Box, Snackbar } from '@mui/material';
import Sidenav from '@/components/Sidenav/Sidenav';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import ContactModal from '@/components/ContactModal/ContactModal';
import { MaterialUIControllerProvider } from '@/context';
import ScrollTopButton from '@/components/ScrollTopButton';
import { useStore } from '@/store';
import '@/app/styles/global.css';

const MainContent = styled(Box)(({ theme }) => ({
  minHeight: '100%',
  display: 'flex',
  flexDirection: 'column',
  gap: 2,

  [theme.breakpoints.down('md')]: {
    marginLeft: '0px'
  }
}));

const inter = Inter({ subsets: ['latin'] });

// const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// };

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false);

  const { isSnackbarOpen, closeSnackbar, snackbarType, snackbarText } = useStore();

  const onToggleSidenav = () => {
    setIsOpen(!isOpen);
  };

  return (
    <html lang="ru">
      <body className={inter.className}>
        {/* <Loader /> */}
        <MaterialUIControllerProvider>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Box sx={{ height: '100%', position: 'relative' }}>
              <Sidenav onToggle={onToggleSidenav} isOpen={isOpen} />

              <MainContent>
                <Header onToggleSidenav={onToggleSidenav} />

                <Box sx={{ flex: '1 0 auto' }}>{children}</Box>

                <Footer />
              </MainContent>

              <ContactModal />
              <ScrollTopButton />

              <Snackbar
                open={isSnackbarOpen}
                anchorOrigin={{ vertical: 'top', horizontal: 'center' }}
                autoHideDuration={3000}
                onClose={closeSnackbar}
              >
                <Alert onClose={closeSnackbar} severity={snackbarType} variant="filled" sx={{ width: '100%' }}>
                  {snackbarText}
                </Alert>
              </Snackbar>
            </Box>
          </ThemeRegistry>
        </MaterialUIControllerProvider>
      </body>
    </html>
  );
}
